#! /bin/sh
bspc rule -r "*"
pgrep -x sxhkd > /dev/null || sxhkd &
#xrandr -s 1366x768 -- dpi 96 &&
#xrandr -s 1920x1080 &&
####		HOME
xrandr --output HDMI3 --primary --mode 1920x1080 --rotate normal --rate 60 --output LVDS1 --off
#xrandr --output HDMI3 --primary --mode 1920x1080 --rotate normal --rate 60 --output LVDS1 --mode 1366x768 --rotate normal --rate 60 --right-of HDMI3
####		WORK
#xrandr --outpout LVDS1 --primary --mode 1366x768 --rotate normal --rate 60 --output HDMI3 --mode 1920x1080 --rotate normal --rate 60 --right-of LVDS1
feh --no-fehbg --bg-scale '/home/akira/Pictures/Backgrounds/Anime & Manga/Chicas Anime Manga/4.jpg' &
#wmname LG3D
####		HOME
bspc monitor -d LVDS1 I II III IV V
####		WORK
#bspc monitor -d LVDS1 I II III
#bspc monitor -d HDMI3 IV V VI

bspc config border_width			2 #3
bspc config normal_border_color		"#008F11"
bspc config focused_border_color	"#00FF41"
bspc config presel_feedback_color	"#00FF41"
bspc config window_gap				3 #5
bspc config split_ratio				0.58

bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config single_monocle			true

bspc config focus_follows_pointer	true
bspc config pointer_modifier		shift
bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action3         resize_corner

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc desktop ^1 -l monocle
bspc desktop ^2 -l monocle
bspc desktop ^3 -l monocle
bspc desktop ^4 -l monocle
#bspc desktop ^5 -l monocle

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Rofi focus=on

xsetroot -cursor_name left_ptr &
