#! /bin/sh
bspc rule -r "*"
pgrep -x sxhkd > /dev/null || sxhkd &
#xrandr -s 1366x768 -- dpi 96 &&
#xrandr -s 1920x1080 &&
xrandr --output HDMI3 --primary --mode 1920x1080 --rotate normal --rate 60 --output LVDS1 --off
#axrandr --outpout LVDS1 --primary --mode 1920x1080 --rotate normal #--output HDMI3 --mode 1920x1080 --rotate normal --right-of LVDS1

feh --no-fehbg --bg-scale '/home/akira/Imágenes/Backgrounds/MyGirl.jpg' &
wmname LG3D

#bspc monitor -d LVDS1 I II III IV V
bspc monitor -d HDMI3 I II III IV

bspc config border_width			3
bspc config normal_border_color		"#008F11"
bspc config focused_border_color	"#00FF41"
bspc config presel_feedback_color	"#00FF41"
bspc config window_gap				6
bspc config split_ratio				0.58

bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config single_monocle			true


bspc config focus_follows_pointer	true
bspc config pointer_modifier		shift
bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action3         resize_corner

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc desktop ^1 -l monocle
bspc desktop ^2 -l monocle
bspc desktop ^3 -l monocle
bspc desktop ^4 -l monocle
#bspc desktop ^5 -l monocle

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &
